/**
 * Styles for the QuestionForm component.
 */

const FONT = '"Palatino Linotype", "Book Antiqua", Palatino, Georgia, serif';

export const questionFormStyles = {
  wrapper: { display: "flex" as const, gap: "32px", alignItems: "flex-start" as const },
  form: { flex: 1, minWidth: "0" },
  field: { marginBottom: "16px" },
  label: {
    display: "block" as const,
    fontSize: "13px",
    color: "#b0a48a",
    marginBottom: "6px",
    fontFamily: FONT,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#2c2218",
    border: "1px solid #3d3225",
    borderRadius: "8px",
    color: "#e8d9b8",
    fontSize: "14px",
    fontFamily: FONT,
    boxSizing: "border-box" as const,
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#2c2218",
    border: "1px solid #3d3225",
    borderRadius: "8px",
    color: "#e8d9b8",
    fontSize: "14px",
    fontFamily: FONT,
    minHeight: "80px",
    resize: "vertical" as const,
    boxSizing: "border-box" as const,
  },
  select: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#2c2218",
    border: "1px solid #3d3225",
    borderRadius: "8px",
    color: "#e8d9b8",
    fontSize: "14px",
    fontFamily: FONT,
    boxSizing: "border-box" as const,
  },
  error: { fontSize: "12px", color: "#e6a8a8", marginTop: "4px", fontFamily: FONT },
  button: {
    padding: "12px 24px",
    backgroundColor: "transparent",
    border: "2px solid #8b7355",
    borderRadius: "8px",
    color: "#e8d9b8",
    fontSize: "14px",
    fontFamily: FONT,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  buttonDisabled: {
    padding: "12px 24px",
    backgroundColor: "transparent",
    border: "2px solid #3d3225",
    borderRadius: "8px",
    color: "#887a62",
    fontSize: "14px",
    fontFamily: FONT,
    cursor: "not-allowed",
  },
  previewSection: { position: "sticky" as const, top: "24px" },
  previewLabel: {
    fontSize: "13px",
    color: "#887a62",
    marginBottom: "12px",
    fontFamily: FONT,
    textTransform: "uppercase" as const,
    letterSpacing: "1px",
  },
} as const;
